#+TITLE:     车
#+AUTHOR:    liweilijie
#+EMAIL:     liweilijie@gmail.com
#+DATE:      2013-05-21 Mon
#+DESCRIPTION: 车
#+KEYWORDS: car
#+CATEGORIES: life
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:{} -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   /liweilijie
#+LINK_HOME: /liweilijie
#+XSLT:
#

* 科目二考试

   这里是我科目二学习的一些心得，明天考试。家里没车练习自己在心里默念一下，个人觉得只要车速降下来，半联动压好。然后注意细节问题应该考试没多大问题。
   调整好心态，明天一定能过的。即使过不了，说明自己学得还不够好，需要继续努力考试，多学习，多思考，为自己与他人的安全负责任。



** 倒库
   从右侧接车，上车后 *调整好座椅* ，一定要看看左右两边的后视镜是不是三分之一车身，三分之二地面。试试离合器，脚刹等。确定好后向窗外的考官示意可以开始了。一定要记住 *右脚不能放在刹车上* ，以免刹车灯亮起，所以脚一定要翘起来做准备，虽然很难受，忍一下吧，谁叫咱们是应试呢。看看车左视镜离黄线的距离，如果都看不到黄线了则可以快打方向盘。
   当车一动起来离黄线上沿十二公分左右就向右打满方向盘。让车慢慢向后倒的同时，看右边后视镜车身与车库右上角边线的距离，当车身与右上角边线距离大于10公分的时候则继续向后倒，
   直到等于10公分的时候压底车速回正方向盘。继续向后倒，当车身与右上角边线距离等于十五公分的时候，这时候车动起来就再次向右打满方向盘慢慢倒入车库。切记回直后的十五公分时间相当短，很快就到了。一定不要倒太多，倒太多就会压右边的线，即便不压右边的线，车右侧屁股也有可以扫到感应器。
   当向右打满方向盘后此时看左后视镜车身与左边边线平行情况，车尾略比车前方窄一点点就回直方向盘，当车左后视镜下沿离黄线有一指的时候踩刹车停车。也可以顺便看一眼车与左边的门把手应该相对即好。这时候车应该停正了。


   然后踩下离合器，摘空档再挂一档，向前方始出，当车头左上角刚好触到黄线的时候向左打满方向盘，车慢慢向左驶去，一定要慢，车一正则迅速回直方向盘，再慢慢向前开，车一触前方铁管则同时踩下离合器与刹车让车停下。这时候观察一下左后视镜下沿与黄线的距离，再挂倒档慢慢起步，当车左后视镜与黄线距离12公分的时候向左打满方向盘，慢慢向后倒车，此时观察左后视镜与车库左上角的距离，如果距离大于10公分则继续向后倒。
   直到10公分的时候回直方向盘，这时候控制好车速，一定要慢慢向后倒，然后往后倒的同时如果夹角到15公分了则向左打满方向盘。记住这时候车一定要动起来再打，否则车有可能向左侧偏太多。然后看车体与车库黄线是否平行，同样车身后侧略窄于前方则可回直方向盘，回直的速度一定要快。且这时候车速也要慢下来，以便观察左后视镜下沿与黄线有一指宽的距离的时候踩离合器与刹车停车。一定要记住在倒车的过程之中右脚不要放在刹车上。要翘起来。

   接下来如果没问题的话就快成功了，挂一档向前开，当车左角触到黄线时向右打满方向盘，车正迅速回直。车速一定要慢。


** 侧方位停车

   上车要领，上车后向考官 *问好* 。然后关上车门，打开 *左转向灯* ，调整好座椅，系好 *安全带* ，观察左右后视镜。踩下离合器，挂一档，松手刹起步。
   当对准前方的箭头后打右转向灯，当车头刚好盖过箭头的最下沿时踩离合与刹车停好车，然后挂倒档，向后倒车，当前头离箭头20公分处向右打满方向盘。
   这时候车要动起来，且车速一定 *要慢* ，然后看左后视镜，能看到车裤最后面的边沿，继续向后倒，直到看到车库右下角(内角)的时候回正方向盘。
   回正的速度要快点，且车速一定要慢，因为回正后不多久将进行下一步操作。回正后看右后视镜，当中央门把手中间正好在黄线正上方时迅速向左后视镜打满方向盘。
   打满后则向前方看，一旦车正则踩下刹车，并且摘空档，为了避免忘了挂档的情况。然后打左转向灯，看左后视镜的道路情况，确保没问题后向左侧出库。
   此时车仍然是左打满状态的。所以无须动方向盘即可。车速一定要慢，当车头刚好靠近黄线的时候迅速回直方向盘，往前再走一点。
   为了确保车右轮不会压线，然后再向右打半圈方向回正车身。


** 坡起

   侧方位完成之后出库准备坡起，在将要上坡前踩点刹车，将车停一下降低车速。然后起步，车身向右一点对准坡起的箭头之后打右转向灯。
   车慢慢向上前进，此时如果车快不动则慢慢抬高一点离合，当车一动则稳住离合，慢慢前进，当车中间一角，眼，杆在一条直线上时迅速踩下离
   合器与刹车将车稳稳停住，记住一定要踩离合器，以免车熄火。然后 *先拉起手刹* ，再 *摘空档* 。

   坡起起步，先 *打左转向灯* ，然后 *挂一档* ， *再松手刹* 。向左带 *半圈方向盘* ，然后左脚慢慢松开离合器，当发动机抖动时则慢慢抬开脚刹，车慢慢起步。
   用眼镜余光观察车右后视镜的边沿离开标杆之后，则可以回正车身。

   上坡的过程中千万别抬离合器太快，极容易熄火，也别将离合器压太低，则容易向后溜车。当车上坡后也不要压下离合器，用一档的速度索制车慢慢下坡。


** 直角

   当车下坡后控制好车速，然后对准直角的箭头后打左转向灯，车速一定要慢慢，当车头一触到黄线则迅速向左打满方向盘，车慢慢向左侧转。
   当车快正时迅速回正方向盘，则完成直角转弯。


** 曲线

   当车从直角出来后，找到曲线前的按钮箱，慢慢靠近按钮箱，离箱有一个后视镜即可。当按钮与自己肩齐时踩下刹车停车，按下按钮，然后 *打开大灯* 。因为前方是隧道。
   打开 *左转向灯* ，因为前方是左转。然后慢慢向前进行隧道曲线行驶，曲线行驶一定要慢，且在转弯时车头尽量靠近变道转。

   当车转出弯道后一定要 *关闭大灯* 。驶出隧道出口。慢慢将车靠边停下。

* 练习


** 手动挡汽车如何起步不熄火?

　　你先是空挡启动汽车,然后迅速踩下离合器,将挡位放在1挡,然后你慢慢松离合器,感觉到松到哪个位置车辆会开始前进,一旦你感觉到车
轮动了,就稳住离合器轻加油门,不要快速松离合器,否则车辆会一冲一冲的.车辆往前行进稳住离合器两秒到三秒,轻踩油门,同时慢慢松离合
器,这样起步就比较稳.换2挡时轻松油门,如果一下子松油门有时候也会车辆前冲的,用一样的办法将挡位换到2挡,一脚离合就可以了.最重要
的是感觉松离合时车辆向前的那个点.只要你把这个点找准了,每次换挡时到达这个点后轻踩油门再松离合,基本上车辆会比较稳了.

　　等待红绿灯是不要紧张,当红灯还有最后5秒时,可以踩离合器,慢慢松离合器,最后一秒时看到前面的车动了,你就轻踩油门,再慢松离合
器.这样不容易熄火。


** 开手动挡的车在上坡中熄火，起步时怎样可以让车不往下滑?

　　朋友，让我来告诉你怎样比较轻松地掌握半坡起步。先踩住刹车，然后踩下离合器，挂入一档。然后慢慢地抬起左脚的离合器踏板，当
抬到一定的位置时，会感觉到发动机有点变声，伴随着车身开始发拌，这时候，也经到了离合点，现在松开刹车踏板，车辆就不会往后退，
然后轻踩油门，车辆就能顺利起步了。等车辆起步后，再慢慢地放开离合器踏板就可以了。是不是很简单，多加练习就可以了。相信你很快
就能掌握了。


** 平地起步

　　确保车停在不拉手刹也不会溜后的路面。操作：踩尽离合，挂一档，先加油(加油)，使转速达1500转以上，稳住油门;快放至总行程的三
分之一，(快放) 慢慢放离合，同时感觉车是否向前动(慢放);当车慢慢向前动时，左脚踩住离合保持不动，右脚加些油(停放-加油)，慢放尽
离合(慢放)(刚好配合油门滞后性)，起步成功!总结：加油--快放--慢放--车动停放-加油--慢放

** 小斜坡起步

　　操作：右脚踩刹车，用一点力就可，但确保车不会溜后;(刹车) 踩尽离合，挂一档，快放离合至总行程三分之一后，慢慢放离合;(快放
--慢放)，注意：当转速表一出现下降时，左脚踩住离合保持不动;(停放)抬头看前面，同时右脚迅速从脚刹踏板移到加速踏板加些油(加油)
，左脚慢慢放离合，当车慢慢向前动时，可以使离合保持一下，再慢慢放离合。(慢放)总结：刹车--快放--慢放--表降停放-加油--慢放

** 大斜坡起步

　　由于坡度较大，需借助手刹起步。操作：拉起手刹;(手刹)，踩尽离合，挂一档，右脚加些油，使转速达1500 转，稳住油门;(加油)快放
至总行程的三分之一后，慢慢放离合;(快放--慢放)注意：当转速表一出现下降时，发动机声音会变沉;左脚踩住离合保持不动(停放)，右脚
再加些油(再加油)，抬头看前面;左脚再慢放一点离合后保持不动，松手刹，起步成功!(再慢放--松手刹)总结：手刹--加油--快放--慢放--
表降停放-再加油--再慢放--松手刹起步方法的掌握是：熟能生巧。
　
